# Maximum amount of letters in one line in message
max-lines-width: 30
# Maximum amount of lines in one message
max-lines-amount: 4
# If limits were reached the end of the message will be shown as ellipsis (...)

# Minimum duration of message
min-duration: 100
# Maximum duration of message
max-duration: 300

# duration = amountOfLetters * readSpeed
# measures in ticks (1 second = 20 ticks)
read-speed: 5